/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Candidate {
  path: string
  locations: Array<number>
  weight: number
}
export declare class GitFile {
  findSimilarFiles(lineno: number): Promise<Array<Candidate>>
}
export declare class LocalGitGraph {
  constructor(repo: string)
  openFile(path: string): Promise<GitFile>
}
